# Generated by Django 5.2.5 on 2026-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_membership_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paymentStatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
