# Generated by Django 5.2.5 on 2026-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='reference',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='selected_plan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='selected_trainer',
            field=models.CharField(max_length=50),
        ),
    ]
