# Generated by Django 5.2.5 on 2026-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_enrollment_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='price',
            new_name='amount_paid',
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(),
        ),
    ]
