# Generated by Django 5.2.5 on 2026-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_rename_price_enrollment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
