# Generated by Django 5.2.5 on 2026-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectdate', models.DateField(auto_now_add=True)),
                ('phonenumber', models.CharField(max_length=12)),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('selectworkout', models.CharField(max_length=100)),
                ('trainedby', models.CharField(max_length=50)),
            ],
        ),
    ]
